version: '3'
services:
  ghost:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2368:2368"
    environment:
      database__client: mysql
      database__connection__host: 192.168.0.175
      database__connection__port: 3308
      database__connection__user: ghost
      database__connection__password: iP115A3*ZA1W3B3g
      database__connection__database: ghost
      url: https://blog.henrime.com
      mail__transport: "SMTP"
      mail__options__host: "email-smtp.ap-southeast-1.amazonaws.com"
      mail__options__port: "465"
      mail__options__service: "SES"
      mail__options__auth__user: "AKIARPEPNA2Q6B2PM4GK"
      mail__options__auth__pass: "BFHf6NjMDa2vM6ATHWU/lFxf9h/WJtz8qjwLMfe5RX9L"
